{
 perl5 => [
           {
            name      => 'perl5',
            enabled   => 1,
            language  => 'Perl 5',
            compiler  => 'perl5',
            vm        => 'perl5',
            f_run     => [$^O =~ /MSWin32/ ? qw( c:/perl/bin/perl           ) : qw( install/bin/perl           )],
            e_run     => [$^O =~ /MSWin32/ ? qw( c:/perl/bin/perl -E        ) : qw( install/bin/perl -E        )],
            show_ver  => [$^O =~ /MSWin32/ ? qw( c:/perl/bin/perl -E say+$] ) : qw( install/bin/perl -E say+$] )],
           },
          ],
 perl6 => [
           {
            name      => 'rakudo-moar',
            enabled   => 1,
            language  => 'Perl 6',
            compiler  => 'rakudo',
            vm        => 'moarvm',
            f_run     => [qw( install/bin/perl6    )],
            e_run     => [qw( install/bin/perl6 -e )],
            show_ver  => [qw( install/bin/perl6 --version )],
           },
           {
            name      => 'rakudo-jvm',
            enabled   => 1,
            language  => 'Perl 6',
            compiler  => 'rakudo',
            vm        => 'jvm',
            f_run     => [qw( ./perl6    )],
            e_run     => [qw( ./perl6 -e )],
            show_ver  => [qw( ./perl6 --version )],
           },
           {
            name      => 'rakudo-js',
            enabled   => 0,
            language  => 'Perl 6',
            compiler  => 'rakudo',
            vm        => 'js',
            f_run     => [qw( ./perl6-js    )],
            e_run     => [qw( ./perl6-js -e )],
            show_ver  => [qw( ./perl6-js --version )],
           },
          ],
 nqp   => [
           {
            name      => 'nqp-jvm',
            enabled   => 1,
            language  => 'NQP',
            compiler  => 'nqp',
            vm        => 'jvm',
            f_run     => [qw( install/bin/nqp-j           )],
            e_run     => [qw( install/bin/nqp-j -e        )],
            show_ver  => [qw( install/bin/nqp-j --version )],
           },
           {
            name      => 'nqp-js',
            enabled   => 0,
            language  => 'NQP',
            compiler  => 'nqp',
            vm        => 'js',
            f_run     => [qw( install/bin/nqp-js           )],
            e_run     => [qw( install/bin/nqp-js -e        )],
            show_ver  => [qw( install/bin/nqp-js --version )],
           },
           {
            name      => 'nqp-moar',
            enabled   => 1,
            language  => 'NQP',
            compiler  => 'nqp',
            vm        => 'moarvm',
            f_run     => [qw( install/bin/nqp-m           )],
            e_run     => [qw( install/bin/nqp-m -e        )],
            show_ver  => [qw( install/bin/nqp-m --version )],
           },
          ],
}
