{
 perl5 => [
           {
            name      => 'perl5',
            enabled   => 1,
            language  => 'Perl 5',
            compiler  => 'perl5',
            vm        => 'perl5',
            f_run     => [qw( install/bin/perl           )],
            e_run     => [qw( install/bin/perl -E        )],
            show_ver  => [qw( install/bin/perl -E say+$] )],
           },
           {
            name      => 'p5.pl',
            enabled   => 1,
            language  => 'Perl 5',
            compiler  => 'perlito5',
            vm        => 'perl5',
            f_run     => [qw( VM -Ilib5 perlito5.pl -Isrc5/lib    )],
            e_run     => [qw( VM -Ilib5 perlito5.pl -Isrc5/lib -e )],
            show_ver  => [qw( VM -Ilib5 perlito5.pl --version     )],
           },
           {
            name      => 'p5.js_node',
            enabled   => 1,
            language  => 'Perl 5',
            compiler  => 'perlito5',
            vm        => 'node.js',
            f_run     => [qw( VM perlito5.js -Isrc5/lib    )],
            e_run     => [qw( VM perlito5.js -Isrc5/lib -e )],
            show_ver  => [qw( VM perlito5.js --version     )],
           },
           {
            name      => 'p5.js_v8',
            enabled   => 1,
            language  => 'Perl 5',
            compiler  => 'perlito5',
            vm        => 'd8',
            f_compile => [qw( VM perlito5.js -- -Isrc5/lib -Cjs    )],
            e_compile => [qw( VM perlito5.js -- -Isrc5/lib -Cjs -e )],
            show_ver  => [qw( VM perlito5.js -- --version          )],
            f_run     => [qw( VM COMPILED -- )],
            e_run     => [qw( VM COMPILED -- )],
           },
          ],
 perl6 => [
           {
            name      => 'rakudo',
            enabled   => 1,
            language  => 'Perl 6',
            compiler  => 'rakudo',
            vm        => 'parrot',
            f_run     => [qw( install/bin/perl6    )],
            e_run     => [qw( install/bin/perl6 -e )],
            show_ver  => [qw( install/bin/perl6 --version )],
           },
           {
            name      => 'rakudo-jvm',
            enabled   => 1,
            language  => 'Perl 6',
            compiler  => 'rakudo-jvm',
            vm        => 'jvm',
            f_run     => [qw( ./perl6    )],
            e_run     => [qw( ./perl6 -e )],
            show_ver  => [qw( ./perl6 --version )],
           },
           {
            name      => 'niecza',
            enabled   => 1,
            language  => 'Perl 6',
            compiler  => 'niecza',
            vm        => 'mono',
            f_run     => [qw( VM run/Niecza.exe    )],
            e_run     => [qw( VM run/Niecza.exe -e )],
            show_ver  => [qw( VM run/Niecza.exe --version )],
           },
           {
            name      => 'p6.pl',
            enabled   => 1,
            language  => 'Perl 6',
            compiler  => 'perlito6',
            vm        => 'perl5',
            f_compile => [qw( VM -Ilib5 perlito6.pl -Cperl5    )],
            e_compile => [qw( VM -Ilib5 perlito6.pl -Cperl5 -e )],
            show_ver  => [qw( VM -Ilib5 perlito6.pl --version  )],
            f_run     => [qw( VM -Ilib5 COMPILED )],
            e_run     => [qw( VM -Ilib5 COMPILED )],
           },
           {
            name      => 'p6.js_v8',
            enabled   => 1,
            language  => 'Perl 6',
            compiler  => 'perlito6',
            vm        => 'd8',
            f_compile => [qw( VM perlito6.js -- -Cjs    )],
            e_compile => [qw( VM perlito6.js -- -Cjs -e )],
            show_ver  => [qw( VM perlito6.js -- --version )],
            f_run     => [qw( VM COMPILED -- )],
            e_run     => [qw( VM COMPILED -- )],
           },
          ],
 nqp   => [
           {
            name      => 'nqp',
            enabled   => 1,
            language  => 'NQP',
            compiler  => 'nqp',
            vm        => 'parrot',
            f_run     => [qw( install/bin/nqp --vmlibs=math_ops    )],
            e_run     => [qw( install/bin/nqp --vmlibs=math_ops -e )],
            show_ver  => [qw( install/bin/nqp --version            )],
           },
           {
            name      => 'nqp-jvm',
            enabled   => 1,
            language  => 'NQP',
            compiler  => 'nqp',
            vm        => 'jvm',
            f_run     => [qw( ./nqp           )],
            e_run     => [qw( ./nqp -e        )],
            show_ver  => [qw( ./nqp --version )],
           },
           {
            name      => 'nqp-moarvm',
            enabled   => 1,
            language  => 'NQP',
            compiler  => 'nqp',
            vm        => 'moarvm',
            dir       => 'nqp-cc',
            f_run     => [qw( install/bin/nqp nqp-moar-cc.nqp           )],
            e_run     => [qw( install/bin/nqp nqp-moar-cc.nqp -e        )],
            show_ver  => [qw( install/bin/nqp nqp-moar-cc.nqp --version )],
           },
           {
            name      => 'rakudo.nqp',
            enabled   => 1,
            language  => 'NQP',
            compiler  => 'rakudo',
            vm        => 'parrot',
            f_run     => [qw( install/bin/perl6    )],
            e_run     => [qw( install/bin/perl6 -e )],
            show_ver  => [qw( install/bin/perl6 --version )],
           },
           {
            name      => 'niecza.nqp',
            enabled   => 1,
            language  => 'NQP',
            compiler  => 'niecza',
            vm        => 'mono',
            f_run     => [qw( VM run/Niecza.exe    )],
            e_run     => [qw( VM run/Niecza.exe -e )],
            show_ver  => [qw( VM run/Niecza.exe --version )],
           },
          ],
}
